-- Datos de las noticias que ya estaban publicadas antes de pasar a Supabase.
-- Generado desde lib/noticias.ts -- correr una sola vez, despues de schema.sql.

insert into noticias (id, tipo, fecha, destacada, series, profesores, escuelita, data)
values
  ('nota-2026-09-bus-nunez', 'nota', '2026-09-12', true, '{}', ARRAY['rodrigo-quintanilla'], false, '{"id":"nota-2026-09-bus-nunez","tipo":"nota","fecha":"2026-09-12","destacada":true,"profesores":["rodrigo-quintanilla"],"titulo":"Buses Núñez se suma como auspiciador del viaje","resumen":"Cerramos un acuerdo con Buses Núñez para el transporte de la delegación. La oferta: un viaje al mes.","cuerpo":["El club cerró un acuerdo de auspicio con Buses Núñez, que aportará traslados para la delegación. La conversación la cerró en terreno el profesor Rodrigo Quintanilla junto a Rodrigo Núñez, hijo del dueño y gerente general de la empresa.","«Yo parezco ahí con el gerente general de la empresa, que se llama Rodrigo Núñez, el futuro dueño de la empresa. Con él nos estábamos estrechando la mano. Por lo tanto, esto puede ser una relación larga en el tiempo, en la medida que hagamos bien todas las cosas», contó Quintanilla.","La oferta inicial de Buses Núñez fue concreta: un viaje al mes para el club.","El club busca ampliar ese compromiso: con el deporte, con los niños, niñas y jóvenes, con sus familias y con las escuelas que están formando a los deportistas del futuro. Buses Núñez quiere ser el bus del Inter — llevando a nuestras delegaciones a moverse por la región, dentro y fuera de Santiago, acompañando a las familias, a los entrenadores y a las jugadoras hasta la cancha rival.","La invitación va en las dos direcciones: quienes viajen con nosotros van a conocer las reglas del deporte, a los profesores que lo enseñan y la historia del club. Los profesores dejan su contacto abierto para coordinar visitas e invitaciones.","Es exactamente el tipo de apoyo que necesitamos — no solo para el Mundialito de diciembre, sino para toda la temporada de traslados a partidos."],"fotos":[{"src":"/images/noticias/bus-nunez-1.webp","alt":"El profesor Quintanilla junto a Rodrigo Núñez frente al bus de Buses Núñez"},{"src":"/images/noticias/bus-nunez-2.webp","alt":"El profesor Quintanilla y Rodrigo Núñez estrechando la mano frente al bus"}],"enlaceExterno":{"label":"Conoce Buses Núñez","url":"https://www.busesnunez.cl/"},"contactoInvitacion":{"profesorId":"rodrigo-quintanilla","mensaje":"Hola, quiero coordinar una invitación con el club a raíz de la alianza con Buses Núñez."}}'::jsonb),
  ('nota-2026-09-fiesta-chilenidad', 'nota', '2026-09-14', true, '{}', ARRAY['rodrigo-quintanilla','rodolfo-oyola'], true, '{"id":"nota-2026-09-fiesta-chilenidad","tipo":"nota","fecha":"2026-09-14","destacada":true,"escuelita":true,"profesores":["rodrigo-quintanilla","rodolfo-oyola"],"titulo":"Fiesta de la Chilenidad de las chuecas","resumen":"La escuelita celebró Fiestas Patrias con chuecas decoradas, banderines y el concurso de la chueca diciochera.","cuerpo":["El lunes 14 de septiembre la escuelita hizo su Fiesta de la Chilenidad: cada niña y niño decoró su chueca con cintas, banderines y motivos patrios, y la trajo al gimnasio para la celebración.","Hubo concurso de la chueca diciochera, y la ganadora fue Jacinta. Felicitaciones a ella, a los profesores que hicieron posible la jornada y a la Ilustre Municipalidad de Lo Espejo, que puso el gimnasio y el taller.","Todas las familias firmaron la autorización de uso de imagen para redes sociales y para el sitio del club antes del evento."],"fotos":[{"src":"/images/noticias/chilenidad-jacinta-ganadora.webp","alt":"Jacinta, ganadora del concurso de la chueca diciochera, con su chueca decorada"},{"src":"/images/noticias/chilenidad-chuecas-decoradas.webp","alt":"Chuecas decoradas con motivos patrios colgadas en la reja de la cancha"},{"src":"/images/noticias/chilenidad-ninas-banderines.webp","alt":"Niñas y niños de la escuelita con sus chuecas decoradas para Fiestas Patrias"},{"src":"/images/noticias/chilenidad-nina-molinillo.webp","alt":"Niña de la escuelita con un molinillo de colores patrios"},{"src":"/images/noticias/chilenidad-profesor-grupo.webp","alt":"El profesor con el grupo de la escuelita y sus chuecas decoradas"}]}'::jsonb),
  ('nota-2026-09-resultados-en-vivo-proximamente', 'nota', '2026-09-15', true, '{}', '{}', false, '{"id":"nota-2026-09-resultados-en-vivo-proximamente","tipo":"nota","fecha":"2026-09-15","destacada":true,"titulo":"Muy pronto: los resultados de la Liga Central, en vivo","resumen":"Estamos integrando ARDI, nuestra mesa de control de broadcast, para publicar acá los resultados de cada partido apenas termina.","cuerpo":["El Internacional Lo Espejo está integrando su sistema de transmisión en vivo, ARDI, con esta página de noticias. La idea: apenas termine un partido de cualquiera de nuestras ocho series en la Liga Central, el resultado —goles, goleadoras, tarjetas, cómo se jugó— va a aparecer acá y en la página de esa serie.","Todavía no está en régimen. Cuando publiquemos el primer resultado real, va a ser acá."],"fotos":[]}'::jsonb)
on conflict (id) do nothing;

